version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: dim_merchants
    columns:
      - name: merchant_id
        tests:
          - unique
          - not_null

  - name: fct_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: merchant_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_merchants')
              field: merchant_id
      - name: gross_revenue
        tests:
          - not_null
